name: tiled
adopt-info: tiled
license: GPL-2.0
base: core18

grade: stable
confinement: strict

apps:
  tiled:
    command: desktop-launch ${SNAP}/usr/bin/tiled
    common-id: org.mapeditor.Tiled.desktop
    plugs: [home, opengl, unity7, network]
  tmxviewer:
    command: desktop-launch ${SNAP}/usr/bin/tmxviewer
    plugs: [home, unity7]
  tmxrasterizer:
    command: desktop-launch ${SNAP}/usr/bin/tmxrasterizer
    plugs: [home, unity7]
  terraingenerator:
    command: desktop-launch ${SNAP}/usr/bin/terraingenerator
    plugs: [home, unity7]

parts:
  tiled:
    plugin: qmake
    qt-version: qt5
    options:
      - PREFIX=/usr
      - SYSTEM_ZSTD=yes
      - CONFIG+=release
    parse-info:
      - org.mapeditor.Tiled.appdata.xml
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe | cut -c 2-)"
    source: .
    build-packages:
      - pkg-config
    # FIXME: Python plugin compiles and loads, but can't find platform libraries
    #  - python-dev
      - qttools5-dev-tools
      - qtdeclarative5-dev
      - zlib1g-dev
      - libzstd-dev
    stage-packages:
      - libqt5quick5
    #  - libpython2.7
      - libzstd1
    after: [desktop-qt5]

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
